### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by jh222vp** [WheresMarco/1DV450-mh222zr-Registreringsapplikation#2]
Hej!
Kör dina instruktioner ifrån punktlistan men när jag sedan försöker starta applikationen så får jag följande felmeddelande:

http://s18.postimg.org/7kp9q1z1l/Capture.png

**Comment by WheresMarco** [comment]
Hej, jag glömde att skriva in i instruktionerna att generera en hemlig nyckel som används för att skapa upp nycklarna för användarna. 

Nu är readme.md uppdaterad med den infon.
