### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by latana** [WheresMarco/1DV450-mh222zr-Registreringsapplikation#6]
Du har gjort valet att den första användaren blir admin. Har du funderat på att seeda upp en admin istället?

Admin kan ta bort sitt egna konto. Med tanke på hur du har byggt upp hur en admin skapas, är detta inte en onödig risk?

**Comment by WheresMarco** [comment]
Förhoppningsvis är du den första som registrerar dig på sidan, men jag håller med om risken. Kommer nog göra en seed för att skapa upp ett admin-konto.
