### ISSUE TITLE
server.pid

### ISSUE THREAD

**Issue by latana** [WheresMarco/1DV450-mh222zr-Registreringsapplikation#8]
Jag kunde inte få igång ditt projekt förrän jag tog bort filen tmp/pids/server.pid

Felmeddelande - "A server is already running. Check /1DV450-mh222zr-Registreringsapplikation-master/tmp/pids/server.pid."

Systemet skapar upp denna filen varje gång jag kör programmet så stänger jag av server måste jag ta bort filen igen.

Är det någonting jag har missat?

**Comment by WheresMarco** [comment]
Vad jag lyckats lista ut så så skapas den filen för att förhindra att du kör samma app två gånger, eller något liknande.

Jag testade att köra igång appen på nitrous.io och fick inga fel när jag följde instruktionerna. 

Kör du servern lokalt kan det vara något config-fel som har uppståt.

**Comment by 1dv450** [comment]
Eller att du råkar ha två servrar igång samtidigt? Jag har dock märkt detta fel ibland när jag testkört applikationer och det har inget med applikationen att gör utan mer en "bugg" när man kör servern.
